spring:
  jackson:
    date-format:
      com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mvc:
    format:
      date: iso
      time: iso-offset
      date-time: iso-offset
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
        order_update: true
        order_insert: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    hikari:
      driver-class-name: ${DB_DRIVER_NAME:net.sf.log4jdbc.sql.jdbcapi.DriverSpy}
      jdbc-url: jdbc:log4jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      password:
  sql:
    init:
      mode: always

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    root: info
